### ISSUE TITLE
Revision 1 Checklist

### ISSUE THREAD

**Issue by Hugemiler** [Klepac-Ceraj-Lab/MicrobiomeAgeModel2024#13]
Tasks/Comments below match the order of the R2R comments, not the manuscript order.

- [ ] **(R1)** External Validation of Model
  - [ ] Adapt _Results_ to clarify LOCOCV
  - [ ] Add Moran's data _Results_ to validation paragraph
  - [ ] Build new version of Fig Supplementary Figure S3
    - [ ] Add the scatterplot with Moran's data highlighted against the original model in the BG
    - [ ] Add the boxplots of errors by age bracker suggested by @kescobo 
    - [ ] Format figure
  - [ ] Add validation methodology to _Methods_
- [ ] **(R1)** Change _Introduction_ to make primary objective clearer
- [ ] **(R2)** Add Discussion paragraph abot how ths model can be used along with uniformized developmental metadata to inform health outcomes
  - [ ] Add a paragraph to R2R explaining why we did not perform the full analysis, and how we sought to instead demonstrate how it could be possible given we had all the available data in the discussion.
  - [ ] Reference Jeff Gordon's Agemodel/malnutrition
  - [ ] Reference CHILD Agemodel/Eczema/AD
- [ ]  **(R2)** Work on Discrete/Continuous Figure 4 reviewer comment
  - [ ] **[FIX]**: Add red/blue triangles to Fig 4 legend
  - [ ] Add R2R and Results bit about the rationale behind discretizing the timepoints
  - [ ] Perform analysis using continuous age data fro longitudinal samples
  - [ ] Build supplementary Figure S4 and Supplementary Note SX to showcase the continuous results
    - [ ] Panel A: Effect sizes and directions of the most increased/decreased functions
      - [ ] Highlight functions repeated from the previous analyses
    - [ ] Panels B-X : Scatterplots of function vs age for select functions relevant to the main text.
- [ ] **(R2)** Change approach of the Dicussion paragraph about MGX vs 16S (see R2R for the tone to be adopted)
- [ ] **(R2)** Add Supplementary Figure SY with the top Variable Importances on all LOCOCV models to compare.
- [ ] **(R2)** Re-run all notebooks and make sure that the RMSE is correct throughout the **entire** text (Abstract-Intro-Results-Discussion-Remarks)
- [ ] **(R2)** Add the extensive meaning of EC (Enzyme Commision number) on its first occurrence in the main text.
- [ ] **(R2)** Review labels of all datasources in main text and supplement and make sure they are all uniform throughout the text
- [ ] **(R2)** Add a Dendrogram to Figure 3 for visualization purposes
- [ ] **(R2)** Adapt Methods and potentially some results to give more detail on the inner working of the model
  - [ ] Hyperparameter optimization methodology
  - [ ] how a prediction is generated.
  - [ ] Transition Score in the Results?

**Comment by Hugemiler** [comment]
R2R:
https://docs.google.com/document/d/1PUBvqLCRFspP10l7HP2nOXJPGU3-OgEmnEJuplpX1X8/edit?usp=drive_link

Second Submission:
https://docs.google.com/document/d/1yIvRgpgISsEwg14btrV-RABchnjN5T_mbBN-M44r-T8/edit?usp=drive_link

**Comment by kescobo** [comment]
Re: Add Discussion paragraph abot how ths model can be used along with uniformized developmental metadata to inform health outcomes

I don't think it needs a whole paragraph. I added a sentence to the last paragraph of the discussion

**Comment by kescobo** [comment]
Close as completed?
